<template>
  <div>
    <ul>
      <li>Tabs组件</li>
      <li>Tabs组件</li>
      <li>Tabs组件</li>
      <li>Tabs组件</li>
      <li>Tabs组件</li>
      <li>Tabs组件</li>
      <li>Tabs组件</li><li>Tabs组件</li>
      <li>Tabs组件</li>
    </ul>
  </div>
</template>